chore(*): convert some "pub" types to "pub(crate)"
The aarch64 build is griping about this:

> error[E0446]: crate-private type `types::ArgError` in public interface
>    --> src/cli.rs:400:5
>     |
> 400 | /     pub fn try_from<T>(args: T) -> Result<Self, ArgError>
> 401 | |     where
> 402 | |         T: IntoIterator<Item = String>,
>     | |_______________________________________^ can't leak crate-private type
>     |
>    ::: src/types.rs:249:1
>     |
> 249 |   pub(crate) enum ArgError {
>     |   ------------------------ `types::ArgError` declared as crate-private
>

There's probably something I could do to ignore it since the other
builds don't seem to mind, but better to fix it I guess.